"""
Otomatik ürün keşfi için arama terimleri.

Kategoriler mevcut DB kategorileriyle uyumlu:
Telefon, Bilgisayar, Tablet, Televizyon, Ev Aleti,
Akıllı Saat, Oyun Konsolu, Kamera, Kulaklık, Beyaz Eşya,
Monitor, Hoparlör, Depolama, Ağ Cihazı, Kişisel Bakım
"""

DISCOVERY_TERMS: dict[str, list[str]] = {
    "telefon": [
        # iPhone 16 serisi
        "iphone 16 pro max 256gb",
        "iphone 16 pro max 512gb",
        "iphone 16 pro max 1tb",
        "iphone 16 pro 256gb",
        "iphone 16 pro 512gb",
        "iphone 16 256gb",
        "iphone 16 128gb",
        "iphone 16 plus 256gb",
        "iphone 16 plus 128gb",
        "iphone 16e 128gb",
        # iPhone 15 serisi
        "iphone 15 pro max 256gb",
        "iphone 15 pro max 512gb",
        "iphone 15 pro max 1tb",
        "iphone 15 pro 256gb",
        "iphone 15 pro 512gb",
        "iphone 15 256gb",
        "iphone 15 128gb",
        "iphone 15 plus 256gb",
        # iPhone 14
        "iphone 14 pro max 256gb",
        "iphone 14 pro 256gb",
        "iphone 14 128gb",
        "iphone 14 plus 128gb",
        # Samsung Galaxy S25
        "samsung galaxy s25 ultra 256gb",
        "samsung galaxy s25 ultra 512gb",
        "samsung galaxy s25 ultra 1tb",
        "samsung galaxy s25 plus 256gb",
        "samsung galaxy s25 plus 512gb",
        "samsung galaxy s25 256gb",
        "samsung galaxy s25 128gb",
        # Samsung Galaxy S24
        "samsung galaxy s24 ultra 256gb",
        "samsung galaxy s24 ultra 512gb",
        "samsung galaxy s24 ultra 1tb",
        "samsung galaxy s24 plus 256gb",
        "samsung galaxy s24 256gb",
        "samsung galaxy s24 128gb",
        # Samsung Galaxy S23
        "samsung galaxy s23 ultra 256gb",
        "samsung galaxy s23 ultra 512gb",
        "samsung galaxy s23 256gb",
        # Samsung A serisi
        "samsung galaxy a55 128gb",
        "samsung galaxy a55 256gb",
        "samsung galaxy a35 128gb",
        "samsung galaxy a35 256gb",
        "samsung galaxy a25 128gb",
        "samsung galaxy a15 128gb",
        # Samsung Fold/Flip
        "samsung galaxy z fold 6 256gb",
        "samsung galaxy z fold 6 512gb",
        "samsung galaxy z fold 5 256gb",
        "samsung galaxy z flip 6 256gb",
        "samsung galaxy z flip 6 512gb",
        "samsung galaxy z flip 5 256gb",
        # Xiaomi
        "xiaomi 15 pro",
        "xiaomi 15 ultra",
        "xiaomi 15",
        "xiaomi 14 ultra",
        "xiaomi 14t pro",
        "xiaomi 14t",
        "xiaomi 14",
        "xiaomi 13t pro",
        "xiaomi redmi note 13 pro plus",
        "xiaomi redmi note 13 pro",
        "xiaomi poco x6 pro",
        "xiaomi poco f6 pro",
        # Google
        "google pixel 9 pro xl",
        "google pixel 9 pro",
        "google pixel 9",
        "google pixel 8 pro",
        "google pixel 8a",
        "google pixel 8",
        # OnePlus
        "oneplus 13 256gb",
        "oneplus 13 512gb",
        "oneplus 12 256gb",
        "oneplus 12 512gb",
        "oneplus nord 4",
        # Diğer
        "oppo find x8 pro",
        "oppo find x7 ultra",
        "oppo reno 12 pro",
        "honor magic 7 pro",
        "honor magic 6 pro",
        "honor 200 pro",
        "nothing phone 2a",
        "nothing phone 2",
        "huawei pura 70 pro",
        "huawei pura 70 ultra",
        "motorola edge 50 ultra",
        "motorola razr 50 ultra",
        "realme gt 6",
        "tecno phantom v fold",
    ],
    "bilgisayar": [
        # MacBook
        "macbook air m4 256gb",
        "macbook air m4 512gb",
        "macbook air m4 16gb",
        "macbook air m3 256gb",
        "macbook air m3 512gb",
        "macbook air m2 256gb",
        "macbook pro m4 pro 512gb",
        "macbook pro m4 pro 1tb",
        "macbook pro m4 max 1tb",
        "macbook pro m4 max 2tb",
        "macbook pro 14 inç m4",
        "macbook pro 16 inç m4",
        "macbook pro 16 inç m4 pro",
        "macbook pro 16 inç m4 max",
        # iMac / Mac
        "imac m4 256gb",
        "imac m4 512gb",
        "mac mini m4 256gb",
        "mac mini m4 512gb",
        "mac mini m4 pro",
        "mac studio m4 max",
        # Lenovo
        "lenovo thinkpad x1 carbon gen 12",
        "lenovo thinkpad x1 carbon gen 11",
        "lenovo thinkpad t14s gen 5",
        "lenovo thinkpad t14s gen 4",
        "lenovo ideapad slim 5 16",
        "lenovo ideapad slim 5 14",
        "lenovo legion pro 5 16",
        "lenovo legion pro 7",
        "lenovo legion 5 pro",
        "lenovo yoga slim 7 14",
        "lenovo yoga 9i 14",
        "lenovo yoga pro 9i",
        "lenovo v15 gen 4",
        # Asus
        "asus zenbook 14 oled ux3405",
        "asus zenbook s 14",
        "asus zenbook duo",
        "asus rog strix g16 2024",
        "asus rog strix g18",
        "asus rog zephyrus g14 2024",
        "asus rog zephyrus g16",
        "asus vivobook 16 2024",
        "asus vivobook s 15",
        "asus vivobook pro 16",
        "asus tuf gaming a15",
        "asus tuf gaming a16",
        "asus proart studiobook",
        # HP
        "hp spectre x360 14 2024",
        "hp spectre x360 16",
        "hp envy 16 2024",
        "hp envy x360 14",
        "hp omen 16 2024",
        "hp omen 17",
        "hp pavilion plus 14",
        "hp pavilion 16",
        "hp elitebook 840 g11",
        "hp victus 16",
        # Dell
        "dell xps 13 2024",
        "dell xps 14 2024",
        "dell xps 16 2024",
        "dell inspiron 14 plus",
        "dell inspiron 16 plus",
        "dell latitude 7440",
        "dell latitude 5540",
        "dell alienware m16 r2",
        "dell alienware x16 r2",
        "dell precision 5680",
        # Diğer
        "monster abra a5 v21",
        "monster tulpar t7 v21",
        "monster semruk s7 v2",
        "msi katana 15 b13v",
        "msi stealth 16 studio",
        "msi creator z16",
        "msi raider ge78 hx",
        "acer swift go 14 2024",
        "acer swift x 14",
        "acer predator helios 16",
        "acer predator helios 18",
        "acer nitro v 15",
        "huawei matebook x pro 2024",
        "huawei matebook 14s",
        "samsung galaxy book 4 pro",
        "samsung galaxy book 4 ultra",
        "razer blade 16",
        "razer blade 14",
        "microsoft surface laptop 7",
        "microsoft surface pro 11",
    ],
    "tablet": [
        "ipad pro m4 11 inç 256gb",
        "ipad pro m4 11 inç 512gb",
        "ipad pro m4 11 inç 1tb",
        "ipad pro m4 13 inç 256gb",
        "ipad pro m4 13 inç 512gb",
        "ipad pro m4 13 inç 1tb",
        "ipad air m2 11 inç 256gb",
        "ipad air m2 11 inç 512gb",
        "ipad air m2 13 inç 256gb",
        "ipad air m2 13 inç 512gb",
        "ipad 10. nesil 64gb",
        "ipad 10. nesil 256gb",
        "ipad mini 7 128gb",
        "ipad mini 7 256gb",
        "apple pencil pro",
        "apple pencil usb-c",
        "magic keyboard ipad pro",
        "samsung galaxy tab s10 ultra 256gb",
        "samsung galaxy tab s10 ultra 512gb",
        "samsung galaxy tab s10 plus 256gb",
        "samsung galaxy tab s10 plus 512gb",
        "samsung galaxy tab s10 fe 128gb",
        "samsung galaxy tab s10 fe 256gb",
        "samsung galaxy tab s9 fe 128gb",
        "samsung galaxy tab s9 ultra 256gb",
        "samsung galaxy tab a9 plus",
        "xiaomi pad 6s pro 256gb",
        "xiaomi pad 6s pro 512gb",
        "xiaomi redmi pad pro",
        "lenovo tab p12 pro",
        "lenovo tab p11 pro gen 2",
        "lenovo yoga tab 11",
        "huawei matepad pro 13",
        "huawei matepad 11.5",
        "onyx boox tab ultra c",
        "onyx boox tab ultra",
        "amazon kindle scribe",
        "amazon kindle paperwhite",
        "microsoft surface go 4",
    ],
    "televizyon": [
        # Samsung
        "samsung neo qled 4k 55 inç qn90d",
        "samsung neo qled 4k 65 inç qn90d",
        "samsung neo qled 4k 75 inç",
        "samsung neo qled 8k 65 inç qn900d",
        "samsung neo qled 8k 75 inç",
        "samsung oled s95d 55 inç",
        "samsung oled s95d 65 inç",
        "samsung the frame 55 inç 2024",
        "samsung the frame 65 inç 2024",
        "samsung the frame 75 inç",
        "samsung crystal uhd 55 inç cu8000",
        "samsung crystal uhd 65 inç cu8000",
        "samsung crystal uhd 75 inç",
        "samsung crystal uhd 43 inç",
        # LG
        "lg oled evo c4 55 inç",
        "lg oled evo c4 65 inç",
        "lg oled evo c4 77 inç",
        "lg oled evo g4 55 inç",
        "lg oled evo g4 65 inç",
        "lg oled evo g4 77 inç",
        "lg oled evo m4 83 inç",
        "lg nanocell 55 inç 2024",
        "lg nanocell 65 inç 2024",
        "lg qned 65 inç 2024",
        "lg qned 75 inç",
        "lg qned mini led 65",
        # Sony
        "sony bravia xr a95l oled 55",
        "sony bravia xr a95l oled 65",
        "sony bravia xr x90l 55 inç",
        "sony bravia xr x90l 65 inç",
        "sony bravia 4k oled 77",
        "sony bravia 9 65 inç",
        "sony bravia 8 55 inç",
        # Diğer
        "philips ambilight oled 55 inç",
        "philips ambilight oled 65 inç",
        "philips ambilight 55 inç 2024",
        "philips ambilight 65 inç 2024",
        "tcl qled 65 inç c745",
        "tcl qled 55 inç c745",
        "tcl mini led 65 inç c845",
        "tcl mini led 75 inç",
        "hisense u7 55 inç 2024",
        "hisense u7 65 inç 2024",
        "hisense u8 mini led 55",
        "hisense u8 mini led 65",
        "hisense u9n mini led",
        "toshiba qled 55 inç",
        "toshiba qled 65 inç",
    ],
    "ev-aleti": [
        # Dyson
        "dyson v15 detect absolute",
        "dyson v15s detect submarine",
        "dyson v12 detect slim absolute",
        "dyson v12 detect slim",
        "dyson v11 absolute",
        "dyson v11 extra",
        "dyson v8 absolute",
        "dyson airwrap complete long",
        "dyson airwrap complete",
        "dyson airwrap multi-styler",
        "dyson supersonic hd15",
        "dyson supersonic nural",
        "dyson purifier cool tp07",
        "dyson purifier hot cool hp07",
        "dyson purifier big quiet",
        "dyson corrale",
        # Robot süpürge
        "irobot roomba j9 plus",
        "irobot roomba combo j9 plus",
        "irobot roomba combo j7 plus",
        "roborock s8 pro ultra",
        "roborock s8 maxv ultra",
        "roborock q revo maxv",
        "roborock q revo",
        "roborock s7 maxv ultra",
        "dreame l20 ultra",
        "dreame x40 ultra",
        "dreame l10s pro ultra",
        "dreame x30 ultra",
        "ecovacs deebot t30 pro omni",
        "ecovacs deebot x2 omni",
        "ecovacs deebot t20 omni",
        "xiaomi robot vacuum x10 plus",
        "samsung jet bot ai plus",
        "narwal freo x ultra",
        # Mutfak
        "philips airfryer xxl hd9870",
        "philips airfryer combi xxl hd9880",
        "philips airfryer 3000 xl",
        "tefal actifry genius xl",
        "tefal easy fry oven",
        "cosori air fryer pro le",
        "ninja foodi dual zone",
        "ninja foodi max",
        "delonghi magnifica evo",
        "delonghi magnifica s",
        "delonghi dinamica plus",
        "delonghi rivelia",
        "nespresso vertuo plus",
        "nespresso vertuo next",
        "nespresso vertuo creatista",
        "nespresso lattissima one",
        "kitchenaid artisan stand mikser 4.8l",
        "kitchenaid artisan stand mikser 3.3l",
        "kenwood titanium chef",
        "bosch optimum mutfak robotu",
        "thermomix tm6",
        "vitamix e310",
    ],
    "beyaz-esya": [
        # Buzdolabı
        "samsung buzdolabı french door rf24",
        "samsung buzdolabı french door rf29",
        "samsung bespoke buzdolabı 4 kapılı",
        "samsung bespoke buzdolabı 2 kapılı",
        "lg instaview buzdolabı french door",
        "lg buzdolabı no frost 70cm",
        "bosch buzdolabı no frost",
        "siemens buzdolabı iq500",
        "siemens buzdolabı iq700",
        "arçelik buzdolabı no frost",
        "beko buzdolabı no frost",
        "vestel buzdolabı no frost",
        "grundig buzdolabı no frost",
        # Bulaşık makinesi
        "bosch bulaşık makinesi sms6",
        "bosch bulaşık makinesi smi6",
        "bosch bulaşık makinesi sps",
        "siemens bulaşık makinesi sn65",
        "siemens bulaşık makinesi sn45",
        "beko bulaşık makinesi",
        "arçelik bulaşık makinesi",
        "vestel bulaşık makinesi",
        # Çamaşır makinesi
        "lg çamaşır makinesi f4v5 10kg",
        "lg çamaşır makinesi f4v5 9kg",
        "samsung çamaşır makinesi addwash 10kg",
        "samsung çamaşır makinesi addwash 9kg",
        "samsung çamaşır makinesi bespoke ai",
        "bosch çamaşır makinesi serie 6",
        "bosch çamaşır makinesi serie 8",
        "siemens çamaşır makinesi iq700",
        "arçelik çamaşır makinesi 10kg",
        "beko çamaşır makinesi 10kg",
        # Kurutma makinesi
        "arçelik kurutma makinesi 9kg",
        "bosch kurutma makinesi wtx87",
        "bosch kurutma makinesi wqg24",
        "siemens kurutma makinesi wq45",
        "samsung kurutmalı çamaşır makinesi 10kg",
        "lg kurutmalı çamaşır makinesi",
        # Ankastre
        "beko ankastre fırın seti",
        "bosch ankastre fırın set hbf",
        "bosch ankastre ocak set",
        "siemens ankastre fırın set",
        "siemens ankastre ocak set",
        "arçelik ankastre fırın set",
        # Klima
        "samsung klima 12000 btu",
        "samsung klima 18000 btu",
        "samsung klima 24000 btu",
        "lg klima dual inverter 12000",
        "lg klima dual inverter 18000",
        "daikin klima 12000 btu",
        "daikin klima 18000 btu",
        "mitsubishi klima 12000 btu",
        "arçelik klima 12000 btu",
    ],
    "akilli-saat": [
        "apple watch ultra 2 49mm",
        "apple watch ultra 2 cellular",
        "apple watch series 10 46mm gps",
        "apple watch series 10 46mm cellular",
        "apple watch series 10 42mm gps",
        "apple watch series 10 42mm cellular",
        "apple watch se 2024 44mm",
        "apple watch se 2024 40mm",
        "samsung galaxy watch 7 ultra 47mm",
        "samsung galaxy watch 7 44mm",
        "samsung galaxy watch 7 40mm",
        "samsung galaxy watch fe 40mm",
        "samsung galaxy watch 6 classic 47mm",
        "garmin fenix 8 amoled 47mm",
        "garmin fenix 8 solar 47mm",
        "garmin fenix 8 51mm",
        "garmin epix pro gen 2 47mm",
        "garmin epix pro gen 2 51mm",
        "garmin venu 3 45mm",
        "garmin venu 3s 41mm",
        "garmin forerunner 965",
        "garmin forerunner 265",
        "garmin forerunner 955",
        "garmin instinct 2x solar",
        "garmin enduro 3",
        "huawei watch gt 5 pro 46mm",
        "huawei watch gt 5 pro 42mm",
        "huawei watch gt 5 46mm",
        "huawei watch gt 5 42mm",
        "huawei watch ultimate design",
        "huawei watch ultimate",
        "google pixel watch 3 45mm",
        "google pixel watch 3 41mm",
        "amazfit t-rex ultra",
        "amazfit gtr 4",
        "coros pace 3",
        "coros vertix 2s",
        "suunto race",
        "withings scanwatch 2",
        "fitbit sense 2",
        "fitbit versa 4",
    ],
    "oyun-konsolu": [
        "playstation 5 pro konsol",
        "playstation 5 pro dijital",
        "playstation 5 slim dijital",
        "playstation 5 slim diskli",
        "playstation 5 dualsense edge",
        "playstation 5 dualsense kontrol",
        "playstation 5 pulse 3d",
        "playstation 5 pulse elite",
        "playstation portal",
        "playstation vr2",
        "xbox series x konsol",
        "xbox series x 2tb",
        "xbox series s konsol",
        "xbox series s 1tb",
        "xbox elite controller series 2 core",
        "xbox wireless controller",
        "nintendo switch oled konsol",
        "nintendo switch oled mario",
        "nintendo switch lite",
        "nintendo switch 2",
        "steam deck oled 512gb",
        "steam deck oled 1tb",
        "steam deck lcd 256gb",
        "asus rog ally x",
        "asus rog ally z1 extreme",
        "lenovo legion go",
        "msi claw",
        "meta quest 3 128gb",
        "meta quest 3 512gb",
        "meta quest 3s 128gb",
        "meta quest 3s 256gb",
        # Oyun aksesuarları
        "razer wolverine v3 pro",
        "scuf reflex pro ps5",
        "elgato stream deck mk2",
        "elgato wave 3 mikrofon",
        "corsair hs80 rgb wireless",
        "steelseries arctis nova pro",
        "hyperx cloud iii wireless",
        "astro a50 wireless gen 4",
    ],
    "kamera": [
        # Sony
        "sony alpha a7 iv body",
        "sony alpha a7 iv kit 28-70",
        "sony alpha a7c ii body",
        "sony alpha a7c ii kit",
        "sony alpha a7r v body",
        "sony alpha a6700 body",
        "sony alpha a6700 kit",
        "sony zv-e10 ii body",
        "sony zv-e10 ii kit",
        "sony zv-1 ii",
        # Canon
        "canon eos r6 mark ii body",
        "canon eos r6 mark ii kit 24-105",
        "canon eos r5 mark ii body",
        "canon eos r50 kit 18-45",
        "canon eos r50 body",
        "canon eos r8 body",
        "canon eos r8 kit",
        "canon eos r100 kit",
        "canon eos r7 body",
        "canon eos r7 kit",
        "canon powershot v10",
        # Fujifilm
        "fujifilm x-t5 body",
        "fujifilm x-t5 kit 18-55",
        "fujifilm x-t50 body",
        "fujifilm x-t50 kit",
        "fujifilm x-s20 body",
        "fujifilm x-s20 kit",
        "fujifilm x100vi",
        "fujifilm x-h2s body",
        "fujifilm gfx 100s ii",
        # Nikon
        "nikon z6 iii body",
        "nikon z6 iii kit 24-70",
        "nikon z8 body",
        "nikon z50 ii kit 16-50",
        "nikon z50 ii body",
        "nikon zf body",
        "nikon zf kit",
        # Panasonic
        "panasonic lumix s5 iix body",
        "panasonic lumix gh7 body",
        "panasonic lumix g9 ii body",
        # Lensler
        "sony fe 24-70mm f2.8 gm ii",
        "sony fe 70-200mm f2.8 gm ii",
        "sony fe 50mm f1.4 gm",
        "canon rf 24-70mm f2.8 l",
        "canon rf 70-200mm f2.8 l",
        "sigma 24-70mm f2.8 dg dn art",
        "tamron 28-75mm f2.8 di iii",
        # Action/Drone
        "gopro hero 13 black",
        "gopro hero 13 black creator",
        "gopro hero 12 black",
        "dji osmo pocket 3",
        "dji osmo pocket 3 creator",
        "dji osmo action 5 pro",
        "dji action 4",
        "dji mini 4 pro fly more",
        "dji mini 4 pro",
        "dji air 3 fly more",
        "dji air 3",
        "dji mavic 3 classic",
        "dji mavic 3 pro",
        "dji avata 2",
        "insta360 x4",
        "insta360 ace pro 2",
        "insta360 one rs",
    ],
    "kulaklik": [
        # Apple
        "apple airpods pro 2 usb-c",
        "apple airpods max usb-c",
        "apple airpods max 2024",
        "apple airpods 4 anc",
        "apple airpods 4",
        # Sony
        "sony wh-1000xm5",
        "sony wh-1000xm4",
        "sony wf-1000xm5",
        "sony wf-1000xm4",
        "sony ult wear",
        "sony ult power",
        "sony inzone h9",
        "sony inzone h7",
        "sony linkbuds s",
        # Samsung
        "samsung galaxy buds 3 pro",
        "samsung galaxy buds 3",
        "samsung galaxy buds fe",
        "samsung galaxy buds 2 pro",
        # Bose
        "bose quietcomfort ultra headphones",
        "bose quietcomfort ultra earbuds",
        "bose quietcomfort headphones 2024",
        "bose quietcomfort earbuds 2024",
        "bose sport earbuds",
        # Sennheiser
        "sennheiser momentum 4 wireless",
        "sennheiser momentum true wireless 4",
        "sennheiser momentum sport",
        "sennheiser hd 660s2",
        "sennheiser ie 600",
        # JBL
        "jbl tour one m2",
        "jbl tour pro 3",
        "jbl live 770nc",
        "jbl live 670nc",
        "jbl tune 770nc",
        "jbl tune 520bt",
        "jbl endurance race 2",
        # Marshall
        "marshall major iv",
        "marshall major v",
        "marshall monitor iii anc",
        "marshall monitor ii anc",
        "marshall motif ii anc",
        "marshall minor iv",
        # Diğer
        "beats studio pro",
        "beats fit pro",
        "beats solo 4",
        "beats studio buds plus",
        "bang olufsen beoplay hx",
        "bang olufsen beoplay ex",
        "bang olufsen beoplay h100",
        "denon ah-gc30",
        "audio-technica ath-m50xbt2",
        "beyerdynamic dt 900 pro x",
        "shure aonic 50 gen 2",
        "jabra elite 10 gen 2",
        "jabra elite 85t",
        "nothing ear 2",
        "nothing ear a",
    ],
    "monitor": [
        # LG
        "lg ultragear oled 27gs95qe",
        "lg ultragear oled 32gs95ue",
        "lg ultragear oled 45gs96qb",
        "lg ultragear 27gp850",
        "lg ultrafine 32un880",
        "lg ultrawide 34wn80c",
        "lg ultrawide 40wp95c",
        "lg dualup 28mq780",
        # Samsung
        "samsung odyssey oled g8 34 inç",
        "samsung odyssey oled g9 49 inç",
        "samsung odyssey g7 28 inç 4k",
        "samsung odyssey g5 34 inç",
        "samsung viewfinity s9 27 5k",
        "samsung viewfinity s8 32 4k",
        "samsung smart monitor m8",
        "samsung smart monitor m7",
        # Dell
        "dell ultrasharp u2724d",
        "dell ultrasharp u3224kb",
        "dell ultrasharp u2723qe",
        "dell ultrasharp u3423we",
        "dell alienware aw3225qf oled",
        "dell alienware aw2725df oled",
        # Asus
        "asus proart pa278qv",
        "asus proart pa329crv",
        "asus proart pa32ucg",
        "asus rog swift oled pg27aqdm",
        "asus rog swift oled pg32ucdm",
        "asus rog swift 360hz pg27aqn",
        # BenQ
        "benq mobiuz ex2710q 27",
        "benq mobiuz ex3210u 32",
        "benq mobiuz ex480uz oled",
        "benq pd2706u 27 4k tasarım",
        "benq pd3220u 32 4k tasarım",
        "benq sw272u 27 fotoğraf",
        # Apple
        "apple studio display",
        "apple pro display xdr",
        # Diğer
        "msi mag 274upf 27 4k",
        "msi meg 342c oled",
        "msi mpg 271qrx qd-oled",
        "huawei mateview gt 34 inç",
        "gigabyte m28u 28 4k",
        "gigabyte aorus fo32u2p oled",
        "aoc agon pro ag274qzm",
        "corsair xeneon 27qhd oled",
    ],
    "hoparlor": [
        # Sonos
        "sonos era 300",
        "sonos era 100",
        "sonos move 2",
        "sonos roam 2",
        "sonos arc soundbar",
        "sonos arc ultra",
        "sonos beam gen 2",
        "sonos ray",
        "sonos sub mini",
        "sonos sub gen 3",
        # Marshall
        "marshall stanmore iii",
        "marshall acton iii",
        "marshall woburn iii",
        "marshall emberton ii",
        "marshall emberton iii",
        "marshall middleton",
        "marshall willen ii",
        "marshall kilburn ii",
        # JBL
        "jbl charge 5",
        "jbl charge 5 wi-fi",
        "jbl boombox 3",
        "jbl boombox 3 wi-fi",
        "jbl flip 6",
        "jbl xtreme 4",
        "jbl xtreme 3",
        "jbl partybox 310",
        "jbl partybox encore",
        "jbl bar 1300",
        "jbl bar 1000",
        "jbl bar 800",
        "jbl authentics 300",
        "jbl authentics 500",
        # Bose
        "bose soundlink max",
        "bose soundlink flex 2",
        "bose soundlink flex",
        "bose soundbar 900",
        "bose soundbar 600",
        "bose ultra soundbar",
        "bose portable home speaker",
        "bose smart speaker 500",
        # Diğer
        "harman kardon aura studio 4",
        "harman kardon onyx studio 8",
        "harman kardon citation 200",
        "bang olufsen beosound a5",
        "bang olufsen beosound 2",
        "bang olufsen beoplay a1",
        "devialet phantom ii 95db",
        "devialet phantom ii 98db",
        "devialet mania",
        "apple homepod 2",
        "apple homepod mini",
        "amazon echo studio",
        "ultimate ears megaboom 4",
        "ultimate ears boom 4",
        "anker soundcore motion x600",
        "samsung soundbar hw-q990d",
        "samsung soundbar hw-q800d",
        "lg soundbar s95qr",
        "sony ht-a9 soundbar",
        "sony ht-a7000 soundbar",
        "denon home 350",
        "yamaha musiccast 50",
    ],
    "depolama": [
        "samsung t9 portable ssd 2tb",
        "samsung t9 portable ssd 4tb",
        "samsung t7 portable ssd 1tb",
        "samsung t7 portable ssd 2tb",
        "samsung t7 shield 2tb",
        "samsung 990 pro 2tb nvme",
        "samsung 990 pro 4tb nvme",
        "samsung 990 evo 2tb nvme",
        "samsung 990 evo plus 2tb",
        "samsung 870 evo 2tb sata",
        "samsung 870 evo 4tb sata",
        "sandisk extreme pro portable ssd 2tb",
        "sandisk extreme pro portable ssd 4tb",
        "sandisk extreme portable ssd 2tb",
        "wd black sn850x 2tb",
        "wd black sn850x 4tb",
        "wd black sn770 2tb",
        "wd my passport 5tb",
        "wd my passport ssd 2tb",
        "wd my book duo 24tb",
        "seagate expansion 5tb",
        "seagate one touch ssd 2tb",
        "seagate ironwolf 8tb nas",
        "seagate firecuda 530 2tb",
        "kingston fury renegade 2tb",
        "kingston fury renegade 4tb",
        "crucial t700 2tb",
        "crucial t500 2tb",
        "crucial x10 pro portable ssd",
        "lexar professional nm800 pro 2tb",
    ],
    "ag-cihazi": [
        "asus rog rapture wifi 7 router gt-be98",
        "asus rog rapture wifi 7 router gt-be19000",
        "asus zenwifi pro et12 mesh",
        "asus zenwifi bt8 mesh wifi 7",
        "tp-link deco be85 mesh wifi 7",
        "tp-link deco be65 mesh wifi 7",
        "tp-link deco xe75 mesh wifi 6e",
        "tp-link archer be900 wifi 7",
        "tp-link archer axe300 wifi 6e",
        "netgear orbi wifi 7 rbe973",
        "netgear orbi wifi 6 rbk853",
        "netgear nighthawk rs700s wifi 7",
        "ubiquiti dream machine pro",
        "ubiquiti unifi express",
        "synology ds224 plus nas",
        "synology ds923 plus nas",
        "synology ds1522 plus nas",
        "synology ds1821 plus nas",
        "qnap ts-464 nas",
        "qnap ts-262 nas",
        "wd my cloud ex2 ultra",
        "wd my cloud pr4100",
    ],
    "kisisel-bakim": [
        # Tıraş
        "philips series 9000 prestige sp9860",
        "philips series 9000 prestige sp9840",
        "philips series 7000 s7786",
        "philips series 5000 s5898",
        "braun series 9 pro 9477cc",
        "braun series 9 pro 9467cc",
        "braun series 7 7171cc",
        "braun series 7 7120s",
        # Diş bakım
        "oral-b io series 9 plus",
        "oral-b io series 9",
        "oral-b io series 7",
        "oral-b io series 6",
        "philips sonicare 9900 prestige",
        "philips sonicare diamondclean 9000",
        "philips sonicare 7900 expert clean",
        # Epilasyon / IPL
        "philips lumea prestige ipl bri956",
        "philips lumea prestige ipl bri949",
        "philips lumea advanced ipl",
        "braun silk expert pro 5 ipl pl5347",
        "braun silk expert pro 5 ipl pl5154",
        "braun silk expert pro 3 ipl",
        "ulike air 10 ipl",
        # Saç bakım
        "dyson airstrait",
        "dyson corrale saç düzleştirici",
        "ghd platinum plus",
        "ghd gold",
        "ghd helios saç kurutma",
        "babyliss steam luxe saç düzleştirici",
        "remington pro-luxe saç kurutma",
        "loreal steampod 4",
    ],
}

# Tüm terimleri düz liste olarak al
def get_all_terms() -> list[tuple[str, str]]:
    """(kategori_slug, arama_terimi) tuple listesi döner."""
    result = []
    for category, terms in DISCOVERY_TERMS.items():
        for term in terms:
            result.append((category, term))
    return result
