"""
Otomatik ürün keşfi için arama terimleri.

Kategoriler mevcut DB kategorileriyle uyumlu:
Telefon, Bilgisayar, Tablet, Televizyon, Ev Aleti,
Akıllı Saat, Oyun Konsolu, Kamera, Kulaklık, Beyaz Eşya,
Monitor, Hoparlör, Depolama, Ağ Cihazı, Kişisel Bakım
"""

DISCOVERY_TERMS: dict[str, list[str]] = {
    "telefon": [
        # iPhone 16 serisi
        "iphone 16 pro max 256gb",
        "iphone 16 pro max 512gb",
        "iphone 16 pro max 1tb",
        "iphone 16 pro 256gb",
        "iphone 16 pro 512gb",
        "iphone 16 256gb",
        "iphone 16 128gb",
        "iphone 16 plus 256gb",
        # iPhone 15 serisi
        "iphone 15 pro max 256gb",
        "iphone 15 pro max 512gb",
        "iphone 15 pro 256gb",
        "iphone 15 256gb",
        # Samsung Galaxy S25
        "samsung galaxy s25 ultra 256gb",
        "samsung galaxy s25 ultra 512gb",
        "samsung galaxy s25 ultra 1tb",
        "samsung galaxy s25 plus 256gb",
        "samsung galaxy s25 256gb",
        # Samsung Galaxy S24
        "samsung galaxy s24 ultra 256gb",
        "samsung galaxy s24 ultra 512gb",
        "samsung galaxy s24 plus",
        "samsung galaxy s24",
        # Samsung Fold/Flip
        "samsung galaxy z fold 6 256gb",
        "samsung galaxy z fold 6 512gb",
        "samsung galaxy z flip 6 256gb",
        "samsung galaxy z flip 6 512gb",
        # Xiaomi
        "xiaomi 15 pro",
        "xiaomi 15 ultra",
        "xiaomi 14 ultra",
        "xiaomi 14t pro",
        "xiaomi 14",
        # Google
        "google pixel 9 pro",
        "google pixel 9 pro xl",
        "google pixel 9",
        # Diğer
        "oneplus 13",
        "oneplus 12",
        "oppo find x8 pro",
        "honor magic 7 pro",
        "honor magic 6 pro",
        "nothing phone 2a",
        "huawei pura 70 pro",
    ],
    "bilgisayar": [
        # MacBook
        "macbook air m4 256gb",
        "macbook air m4 512gb",
        "macbook air m3 256gb",
        "macbook air m3 512gb",
        "macbook pro m4 pro 512gb",
        "macbook pro m4 pro 1tb",
        "macbook pro m4 max",
        "macbook pro 16 inç m4",
        # Lenovo
        "lenovo thinkpad x1 carbon gen 12",
        "lenovo thinkpad t14s",
        "lenovo ideapad slim 5 16",
        "lenovo legion pro 5",
        "lenovo yoga slim 7",
        # Asus
        "asus zenbook 14 oled",
        "asus rog strix g16",
        "asus rog zephyrus g14",
        "asus vivobook 16",
        "asus tuf gaming laptop",
        # HP
        "hp spectre x360 14",
        "hp envy 16",
        "hp omen 16 gaming",
        "hp pavilion 16",
        # Dell
        "dell xps 14",
        "dell xps 16",
        "dell inspiron 16",
        "dell latitude 7440",
        # Diğer
        "monster abra a5 v21",
        "monster tulpar t7 v21",
        "msi katana 15",
        "msi stealth 16",
        "acer swift go 14",
        "acer predator helios",
        "huawei matebook x pro",
    ],
    "tablet": [
        "ipad pro m4 11 inç",
        "ipad pro m4 13 inç",
        "ipad pro m4 256gb",
        "ipad pro m4 512gb",
        "ipad air m2 256gb",
        "ipad air m2 512gb",
        "ipad 10. nesil 64gb",
        "ipad 10. nesil 256gb",
        "ipad mini 7",
        "samsung galaxy tab s10 ultra 256gb",
        "samsung galaxy tab s10 plus 256gb",
        "samsung galaxy tab s10 fe",
        "samsung galaxy tab s9 fe 128gb",
        "samsung galaxy tab s9 ultra",
        "xiaomi pad 6s pro 256gb",
        "lenovo tab p12 pro",
        "huawei matepad pro 13",
        "onyx boox tab ultra",
    ],
    "televizyon": [
        # Samsung
        "samsung neo qled 4k 55 inç",
        "samsung neo qled 4k 65 inç",
        "samsung neo qled 8k 65 inç",
        "samsung the frame 55 inç",
        "samsung the frame 65 inç",
        "samsung crystal uhd 55 inç",
        "samsung crystal uhd 65 inç",
        # LG
        "lg oled evo c4 55 inç",
        "lg oled evo c4 65 inç",
        "lg oled evo g4 55 inç",
        "lg oled evo g4 65 inç",
        "lg nanocell 55 inç",
        "lg qned 65 inç",
        # Sony
        "sony bravia xr 55 inç",
        "sony bravia xr 65 inç",
        "sony bravia 4k oled",
        # Diğer
        "philips ambilight 55 inç",
        "philips ambilight 65 inç",
        "tcl qled 65 inç",
        "tcl qled 55 inç",
        "hisense u7 55 inç",
        "hisense u7 65 inç",
        "hisense u8 mini led",
    ],
    "ev-aleti": [
        # Dyson
        "dyson v15 detect absolute",
        "dyson v15s detect submarine",
        "dyson v12 detect slim absolute",
        "dyson v11 absolute",
        "dyson airwrap complete long",
        "dyson airwrap complete",
        "dyson supersonic hd15",
        "dyson purifier cool",
        "dyson purifier hot cool",
        # Robot süpürge
        "irobot roomba j9 plus",
        "irobot roomba combo j7",
        "roborock s8 pro ultra",
        "roborock s8 maxv ultra",
        "roborock q revo",
        "dreame l20 ultra",
        "dreame x40 ultra",
        "ecovacs deebot t30 pro",
        # Mutfak
        "philips airfryer xxl hd9870",
        "philips airfryer combi xxl",
        "delonghi magnifica evo",
        "delonghi magnifica s",
        "nespresso vertuo plus",
        "nespresso vertuo next",
        "kitchenaid artisan stand mikser",
        "thermomix tm6",
    ],
    "beyaz-esya": [
        "samsung buzdolabı french door",
        "samsung bespoke buzdolabı",
        "lg instaview buzdolabı",
        "bosch bulaşık makinesi sms",
        "bosch bulaşık makinesi smi",
        "siemens bulaşık makinesi",
        "lg çamaşır makinesi f4v5",
        "samsung çamaşır makinesi addwash",
        "arçelik kurutma makinesi",
        "bosch kurutma makinesi",
        "samsung kurutmalı çamaşır makinesi",
        "beko ankastre fırın seti",
        "bosch ankastre set",
        "siemens ankastre fırın",
    ],
    "akilli-saat": [
        "apple watch ultra 2 49mm",
        "apple watch series 10 46mm",
        "apple watch series 10 42mm",
        "apple watch se 2024",
        "samsung galaxy watch 7 ultra",
        "samsung galaxy watch 7 44mm",
        "samsung galaxy watch 7 40mm",
        "samsung galaxy watch fe",
        "garmin fenix 8 amoled",
        "garmin fenix 8 solar",
        "garmin epix pro gen 2",
        "garmin venu 3",
        "garmin venu 3s",
        "garmin forerunner 965",
        "huawei watch gt 5 pro",
        "huawei watch gt 5 46mm",
        "huawei watch ultimate",
        "google pixel watch 3",
    ],
    "oyun-konsolu": [
        "playstation 5 pro konsol",
        "playstation 5 slim dijital",
        "playstation 5 slim diskli",
        "playstation 5 dualsense edge",
        "playstation 5 dualsense kontrol",
        "playstation portal",
        "xbox series x konsol",
        "xbox series s konsol",
        "xbox elite controller series 2",
        "nintendo switch oled konsol",
        "nintendo switch lite",
        "steam deck oled 512gb",
        "steam deck oled 1tb",
        "meta quest 3 128gb",
        "meta quest 3 512gb",
        "meta quest 3s",
    ],
    "kamera": [
        # Sony
        "sony alpha a7 iv body",
        "sony alpha a7 iv kit",
        "sony alpha a7c ii body",
        "sony alpha a7r v",
        "sony zv-e10 ii",
        # Canon
        "canon eos r6 mark ii body",
        "canon eos r6 mark ii kit",
        "canon eos r50 kit",
        "canon eos r8 body",
        "canon eos r100",
        # Fujifilm
        "fujifilm x-t5 body",
        "fujifilm x-t5 kit",
        "fujifilm x-s20",
        "fujifilm x100vi",
        # Nikon
        "nikon z6 iii body",
        "nikon z8 body",
        "nikon z50 ii kit",
        # Action/Drone
        "gopro hero 13 black",
        "gopro hero 12 black",
        "dji osmo pocket 3",
        "dji osmo action 5 pro",
        "dji mini 4 pro",
        "dji air 3",
        "dji mavic 3 classic",
        "insta360 x4",
    ],
    "kulaklik": [
        # Apple
        "apple airpods pro 2 usb-c",
        "apple airpods max usb-c",
        "apple airpods 4 anc",
        "apple airpods 4",
        # Sony
        "sony wh-1000xm5",
        "sony wh-1000xm4",
        "sony wf-1000xm5",
        "sony ult wear",
        # Samsung
        "samsung galaxy buds 3 pro",
        "samsung galaxy buds 3",
        "samsung galaxy buds fe",
        # Bose
        "bose quietcomfort ultra headphones",
        "bose quietcomfort ultra earbuds",
        "bose quietcomfort headphones",
        "bose quietcomfort earbuds",
        # Diğer
        "sennheiser momentum 4 wireless",
        "sennheiser momentum true wireless 4",
        "jbl tour one m2",
        "jbl tour pro 3",
        "jbl live 770nc",
        "marshall major iv",
        "marshall monitor ii anc",
        "beats studio pro",
        "beats fit pro",
        "bang olufsen beoplay hx",
    ],
    "monitor": [
        "lg ultragear oled 27 inç",
        "lg ultragear oled 32 inç",
        "lg ultragear oled 45 inç",
        "samsung odyssey oled g8 34",
        "samsung odyssey oled g9 49",
        "samsung viewfinity s9 27",
        "dell ultrasharp u2724d",
        "dell ultrasharp u3224kb",
        "asus proart pa278qv",
        "asus proart pa329crv",
        "asus rog swift oled",
        "benq mobiuz ex2710q",
        "benq mobiuz ex3210u",
        "benq pd2706u tasarım monitör",
        "apple studio display",
        "apple pro display xdr",
        "msi mag 274upf",
        "huawei mateview gt 34",
    ],
    "hoparlor": [
        "sonos era 300",
        "sonos era 100",
        "sonos move 2",
        "sonos arc soundbar",
        "sonos beam gen 2",
        "marshall stanmore iii",
        "marshall acton iii",
        "marshall woburn iii",
        "marshall emberton ii",
        "jbl charge 5",
        "jbl boombox 3",
        "jbl flip 6",
        "jbl xtreme 4",
        "jbl partybox 310",
        "bose soundlink max",
        "bose soundlink flex",
        "bose soundbar 900",
        "bose soundbar 600",
        "harman kardon aura studio 4",
        "harman kardon onyx studio 8",
        "bang olufsen beosound a5",
        "devialet phantom ii",
    ],
    "depolama": [
        "samsung t9 portable ssd 2tb",
        "samsung t7 portable ssd 1tb",
        "samsung 990 pro 2tb",
        "samsung 990 evo 2tb",
        "sandisk extreme pro portable ssd",
        "wd black sn850x 2tb",
        "wd my passport 5tb",
        "seagate expansion 5tb",
        "kingston fury renegade 2tb",
    ],
    "ag-cihazi": [
        "asus rog rapture wifi 7 router",
        "asus zenwifi pro et12 mesh",
        "tp-link deco be85 mesh wifi 7",
        "tp-link archer be900",
        "netgear orbi wifi 7",
        "synology ds224 plus nas",
        "synology ds923 plus nas",
    ],
    "kisisel-bakim": [
        "philips series 9000 prestige",
        "philips series 7000",
        "braun series 9 pro",
        "braun series 7",
        "oral-b io series 9",
        "oral-b io series 7",
        "philips sonicare 9900 prestige",
        "philips lumea prestige ipl",
        "braun silk expert pro 5 ipl",
        "dyson airstrait",
        "ghd platinum plus",
    ],
}

# Tüm terimleri düz liste olarak al
def get_all_terms() -> list[tuple[str, str]]:
    """(kategori_slug, arama_terimi) tuple listesi döner."""
    result = []
    for category, terms in DISCOVERY_TERMS.items():
        for term in terms:
            result.append((category, term))
    return result
